version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
