# Generated by Django 3.1 on 2021-05-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='period_interval',
            field=models.SmallIntegerField(default=1),
        ),
    ]
